### PR TITLE
fix/rust: fix rust ci bug

### PR DESCRIPTION
**Pull request by caicancai**
## Related issue number

Closes #xxxx

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://github.com/alipay/fury/blob/main/CONTRIBUTING.rst) for how to run them

### CODE REVIEW

**Comment by caicancai** [comment]
https://github.com/alipay/fury/pull/1138

**Comment by caicancai** [comment]
捕获
Locally tested

cc @wangweipeng2 @chaokunyang

**Comment by wangweipeng2** [comment]
> 捕获 Locally tested
> cc @wangweipeng2 @chaokunyang
@caicancai 
As the report says, it seems like the workspace cannot include dirty files. Maybe you should create a shell script out of the workspace and run it?

**Comment by caicancai** [comment]
> > 捕获 Locally tested
> > cc @wangweipeng2 @chaokunyang
> > @caicancai
> > As the report says, it seems like the workspace cannot include dirty files. Maybe you should create a shell script out of the workspace and run it?

Yes, it can't include dirty files, we should allow dirty files, this dirty file is created and tested by myself

**Comment by caicancai** [comment]
If I don't check for dirty files, I need to remove cargo clippy --workspace --all-features --all-targets --fix

**Comment by wangweipeng2** [comment]
> > > 捕获 Locally tested
> 
> > > cc @wangweipeng2 @chaokunyang
> 
> > > @caicancai
> 
> > > As the report says, it seems like the workspace cannot include dirty files? Maybe you should create a shell script out of the workspace and run it?
> 
> 
> 
> Yes, it can't include dirty files, we should allow dirty files, this dirty file is created and tested by myself

May be you can create a temp test bash file out of the workspace?

**Comment by caicancai** [comment]
Maybe now allowing dirty files is a good choice, I see a lot of projects don't actually require it

**Comment by wangweipeng2** [comment]
> Maybe now allowing dirty files is a good choice, I see a lot of projects don't actually require it

Both options are fine. as long as they are tested correctly

**Comment by caicancai** [comment]
> > Maybe now allowing dirty files is a good choice, I see a lot of projects don't actually require it
> 
> Both options are fine. as long as they are tested correctly

Thank you for your review and reply. At present, ci will not pass if the test fails

**Comment by caicancai** [comment]
cc @chaokunyang

**Review by wangweipeng2 — APPROVED** [review]
LGTM

**Pull request merged**
