### PR TITLE
[Doc] add apache license section to readme

### PR DESCRIPTION
**Pull request by caicancai**
## What do these changes do?

add apache license on README

## Related issue number

Closes #xxxx

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://github.com/alipay/fury/blob/main/CONTRIBUTING.rst) for how to run them

### CODE REVIEW

**Comment by caicancai** [comment]
Maybe we can check the license in the CLI check, I don't know if there is such a measure at the moment

**Comment by caicancai** [comment]
cc @chaokunyang

**Comment by chaokunyang** [comment]
@caicancai We've already has the license header check in CI.

**Comment by caicancai** [comment]
> @caicancai We've already has the license header check in CI.

thank your reply . This is a good idea

**Review by chaokunyang — APPROVED** [review]
LGTM

**Pull request merged**
