### PR TITLE
[Improve][Doc] add environment requirement

### PR DESCRIPTION
**Pull request by caicancai**
## What do these changes do?

add java environment requirement
If C++, Python, and Go have version requirements, I can also add to this PR

## Related issue number

Closes #xxxx

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://github.com/alipay/fury/blob/main/CONTRIBUTING.rst) for how to run them

### CODE REVIEW

**Comment by caicancai** [comment]
cc @chaokunyang

**Comment by chaokunyang** [comment]
- C++ need to use bazel 4.2, cpp 11+
- Golang need go1.3+
- Python need python3.6+
- Dost Rust/Nodejs has version requirements? @wangweipeng2

**Comment by caicancai** [comment]
@chaokunyang There are currently no JS and Rust tutorials in the documentation, so you can wait to improve the documentation later

**Comment by wangweipeng2** [comment]
> * C++ need to use bazel 4.2, cpp 11+
> * Golang need go1.3+
> * Python need python3.6+
> * Dost Rust/Nodejs has version requirements? @wangweipeng2
 
- Browser needle  Chrome 40+
- Nodejs need  14+
- Rust need  1.65+

**Comment by chaokunyang** [comment]
> @chaokunyang There are currently no JS and Rust tutorials in the documentation, so you can wait to improve the documentation later

@wangweipeng2 just comment nodejs rust requirements, could you update it in this pr. Further updates can be put in future pr

**Comment by chaokunyang** [comment]
OK, we can update it later when js/rust guide ready.

**Review by chaokunyang — APPROVED** [review]
LGTM

**Pull request merged**
