### PR TITLE
rust/ci: improve rust ci

### PR DESCRIPTION
**Pull request by caicancai**
## Related issue number

Closes #xxxx

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://github.com/alipay/fury/blob/main/CONTRIBUTING.rst) for how to run them

### CODE REVIEW

**Comment by caicancai** [comment]
If the cargo procedure fails, the ci should not pass

**Review by wangweipeng2 — APPROVED** [review]
LGTM

**Comment by caicancai** [comment]
@wangweipeng2 I'm actually not sure if this is the right way to write it, but I will do some verification in the next few days to optimize ci

**Comment by wangweipeng2** [comment]
> @wangweipeng2 I'm actually not sure if this is the right way to write it, but I will do some verification in the next few days to optimize ci
> 
> cc @chaokunyang

Or, you can test it on your local machine? Just some advice. 😁

**Comment by caicancai** [comment]
> > @wangweipeng2 I'm actually not sure if this is the right way to write it, but I will do some verification in the next few days to optimize ci
> > cc @chaokunyang
> 
> Or, you can test it on your local machine? Just some advice. 😁

Good idea, I'll test rust's ci individually on the local machine

**Pull request merged**
