### PR TITLE
[Improve][Doc] rename contribute to build

### PR DESCRIPTION
**Pull request by caicancai**
## What do these changes do?

rename contribute to build
The GitHub description already has a website and does not need to be put in the README

## Related issue number

Closes #xxxx

## Check code requirements

- [ ] tests added / passed (if needed)
- [ ] Ensure all linting tests pass, see [here](https://github.com/alipay/fury/blob/main/CONTRIBUTING.rst) for how to run them

### CODE REVIEW

**Comment by caicancai** [comment]
cc @chaokunyang

**Comment by chaokunyang** [comment]
Contribution part are necessary, actually it's part of github `Community Standards`:

image

And projects such as pytorch/tf/arrow all have this part:
image

image

image

**Comment by caicancai** [comment]
> Contribution part are necessary, actually it's part of github `Community Standards`:
> 
> image
> 
> And projects such as pytorch/tf/arrow all have this part: image
> 
> image
> 
> image

Thank you for your review. It seems to me that contribute and build documents put them together. Is it a better choice to split them?

**Comment by caicancai** [comment]
I will close this pr and modify it in the new pr

**Pull request closed without merging**
